name: deploy-to-argo-via-actions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: dev or prod
        required: true
        default: dev

permissions:
  contents: write
  
jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      # - name: Update files
      #   run: |
      #     echo "do updates here"
          
      - name: Select values file
        run: |
            if [ "${{ inputs.environment }}" = "dev" ]; then
            echo "REPLICA_COUNT=1" >> $GITHUB_ENV
            echo "ENV_NAME=dev" >> $GITHUB_ENV
            else
            echo "REPLICA_COUNT=3" >> $GITHUB_ENV
            echo "ENV_NAME=prod" >> $GITHUB_ENV
            fi

      - name: Update deployment.yaml
        run: |
          yq -i '.spec.replicas = env(REPLICA_COUNT)' guestbook/guestbook-ui-deployment.yaml
          yq -i '.spec.template.metadata.labels.env = env(ENV_NAME)' guestbook/guestbook-ui-deployment.yaml

      - name: Update service.yaml if needed
        run: |
          yq -i '.metadata.labels.env = env(ENV_NAME)' guestbook/guestbook-ui-svc.yaml
          yq -i '.spec.selector.env = env(ENV_NAME)' guestbook/guestbook-ui-svc.yaml


      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email "ccwh@ust.hk"
          git add guestbook/guestbook-ui-deployment.yaml guestbook/guestbook-ui-svc.yaml
          git commit --allow-empty -m "update ${{ inputs.environment }} values"
          git push
          
  sync-prod:
    runs-on: ubuntu-latest
    needs: update-manifest
    if: ${{ inputs.environment == 'prod' }}
    environment: prod
    steps:
      - name: Install ArgoCD
        uses: syntaqx/setup-argocd@v1
                
      - name: Sync ArgoCD app
        env:
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_SERVER: argocd-akslocal5.hkust.edu.hk
        run: |
           argocd app sync test-sep-argo-project \
             --server "$ARGOCD_SERVER" \
             --auth-token "$ARGOCD_AUTH_TOKEN" \
             --grpc-web
           argocd app wait test-sep-argo-project \
             --server "$ARGOCD_SERVER" \
             --auth-token "$ARGOCD_AUTH_TOKEN" \
             --health --timeout 300
